services:
  backend:
    env_file:
      - .env

    build:
      context: ./backend

    container_name: confiq-backend

    restart: unless-stopped

    expose:
      - "8089"

    volumes:
      - ./backend/data:/app/data


  frontend:
    build:
      context: ./frontend

    container_name: confiq-frontend

    restart: unless-stopped

    expose:
      - "80"


  proxy:
    image: nginx:alpine

    container_name: confiq-proxy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - backend